DROP TABLE IF EXISTS COMPANY_MAP  ;
DROP TABLE IF EXISTS TRAINEE_MAP;
DROP TABLE IF EXISTS COURSE_MAP;
DROP TABLE IF EXISTS ATTENDEE_MAP;
DROP TABLE IF EXISTS COURSE_INS;
DROP TABLE IF EXISTS BOOKED_COURSE_MAP;
DROP TABLE IF EXISTS BOOKED_COURSE_CONTENT;

CREATE TABLE COMPANY_MAP(
    ID INT NOT NULL,
    ORIG_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS1 VARCHAR(255),
    ADDRESS2 VARCHAR(255),
    ADDRESS3 VARCHAR(255),
    ADDRESS4 VARCHAR(255),
    POSTCODE VARCHAR(255),
    PRIMARY KEY (ID)
)
;

CREATE TABLE TRAINEE_MAP(
    ID INT NOT NULL,
    ORIG_ID INT NOT NULL,
    COMPANY_ID INT NOT NULL,
    FORENAME VARCHAR(255),
    SURNAME VARCHAR(255),
    PRIMARY KEY (ID)
)
;

CREATE TABLE COURSE_MAP(
    ID INT NOT NULL,
    ORIG_ID INT NOT NULL,
    COURSE_TITLE VARCHAR(255),
    CERTIFICATE_PREFIX VARCHAR(255),
    CERTIFICATE_COUNT VARCHAR(255),
    PRIMARY KEY (ID)
)
;

CREATE TABLE ATTENDEE_MAP(
    ID INT NOT NULL,
    ORIG_ID INT NOT NULL,
    DELEGATE_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    PASSED BOOL,
    THEORY INT,
    PRACTICAL_FAULTS INT,
    FAIL_REASON VARCHAR(255),
    FURTHER_TRAINING VARCHAR(255),
    PRIMARY KEY (ID)
)
;

CREATE TABLE COURSE_INS(
    ID INT NOT NULL,
    ORIG_ID INT NOT NULL,
    COURSE_TEMPLATE_ID INT,
    INSTANCE_NUMBNER INT,
    DESCRIPTION VARCHAR(255),
    START_DATE DATE,
    END_DATE DATE,
    DAYS INT,
    HELD_AT VARCHAR(255),
    EXAMINER INT,
    PRIMARY KEY (ID)
)
;

CREATE TABLE BOOKED_COURSE_MAP(
    ID bigint auto_increment,
    ORIG_COURSE_ID INT NOT NULL,
    MAPPED_COURSE_ID INT,
    TEMPLATE_ID INT NOT NULL,
    COURSE_REF VARCHAR(255),
    START_DATE DATE,
    END_DATE DATE,
    PRIMARY KEY (ID)
)
;

CREATE TABLE BOOKED_COURSE_CONTENT
(
    ID bigint auto_increment,
    ORIG_COURSE_ID INT NOT NULL,
    MAPPED_COURSE_ID INT,
    EQUIPMENT VARCHAR(255),
    MODEL VARCHAR(255),
    CAPACITY VARCHAR(255),
    ATTACHMENT VARCHAR(255),
    COURSE_ELEMENTS VARCHAR,
    PRIMARY KEY (ID)
)
;

CREATE INDEX COURSE_IDX ON BOOKED_COURSE_CONTENT(MAPPED_COURSE_ID);